// <auto-generated />
using FilesMonitoringServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace FilesMonitoringServer.Migrations
{
    [DbContext(typeof(TrackerDb))]
    [Migration("20180122103116_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FilesMonitoringServer.Change", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Content");

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("FileId");

                    b.Property<string>("OldFullName");

                    b.Property<string>("OldName");

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("Changes");
                });

            modelBuilder.Entity("FilesMonitoringServer.File", b =>
                {
                    b.Property<int>("FileId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FileName")
                        .IsRequired();

                    b.Property<string>("FilePath");

                    b.Property<string>("FullName")
                        .IsRequired();

                    b.Property<int>("TrackerId");

                    b.HasKey("FileId");

                    b.HasIndex("TrackerId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("FilesMonitoringServer.Tracker", b =>
                {
                    b.Property<int>("TrackerId");

                    b.HasKey("TrackerId");

                    b.ToTable("Trackers");
                });

            modelBuilder.Entity("FilesMonitoringServer.Change", b =>
                {
                    b.HasOne("FilesMonitoringServer.File", "File")
                        .WithMany("ChangeList")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FilesMonitoringServer.File", b =>
                {
                    b.HasOne("FilesMonitoringServer.Tracker", "Tracker")
                        .WithMany("FileList")
                        .HasForeignKey("TrackerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
